### ISSUE TITLE
CSS-08

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy-adaptive/2381535-cat-energy-30#15]
Для `body` не нужно обнулять `padding` — он и так по дефолту нулевой.

А вот этот кусок кода рекомендую добавить и всегда добавлять в любой проект — он обезопасит от поломки лейаута из-за вставки из админки какой-нибудь огромной картинки, с ним она будет всегда не больше размера родителя, с адекватными размерами не сломанным соотношением сторон.

```css
img { 
  max-width: 100%;
  height: auto;
  object-fit: contain;
}
```
